### ISSUE TITLE
Cavalier 'Unwavering Mark' doesn't read as optional

### ISSUE THREAD

**Issue by Smashman** [safety-orange/Imports-for-MPMB-s-Character-Sheet#18]
> If I hit a creature with a melee weapon attack, **I mark it until the end of my next turn**
> While it is within 5 ft of me, a marked target has disadv. on attacks not directed at me
> If it damages anybody but me, I can make a special melee attack vs. it in my next turn
> This takes a bonus action, but has adv. and adds half my fighter level to the damage
> A mark ends early if I'm incapacitated, die, or somebody else marks the target

I appreciate that this may be due to space restrictions, however on initial read, I was unsure if the feature is optional. I had to break out the book to verify.
Thanks.

**Comment by safety-orange** [comment]
The fact that it says "Strength modifier per long rest" in the Class Features section and that it is also listed in the Limited Features section didn't make it clear that it is optional?

As far as I know, nowhere in the official D&D 5e materials is something a limited feature while also being mandatory.

**Comment by Smashman** [comment]
I think it's an assumption that, while I did make, wasn't one that I was comfortable making. Most features that are optional state as much in the class feature area.
If you believe it's a non-issue, feel free to close this, just thought I'd make you aware in case you thought it was a problem.

**Comment by safety-orange** [comment]
My fear is that if I make this an issue, there are a lot more features with the same problem.

And all of them had the word "can" omitted because of space constraints.

Correct me if I'm wrong, but I think that all the things that are mandatory (which are very few) have that explicitly named in the class feature description in the code here. So it is safe to assume that everything is optional, unless otherwise specified. This is also in line with the general rules of D&D 5e.
