### ISSUE TITLE
"The script '2020/03/06 - all_WotC_pub+UA.js' is faulty"

### ISSUE THREAD

**Issue by AllTheAnonimity** [safety-orange/Imports-for-MPMB-s-Character-Sheet#40]
When trying to import the new 2020/03/06 - all_WotC_pub+UA.js file I get an error stating the following: "ReferenceError: MagicItemList is not defined". I have no idea how to fix this! Any suggestions would be much appreciated, thank you in advance!

**Comment by safety-orange** [comment]
That error means that you are importing the script into a version of the sheet that is too old for the script. As you didn't link to which file you are using, I'll assume you are using the one from [the v13 folder](https://github.com/safety-orange/Imports-for-MPMB-s-Character-Sheet/tree/master/WotC%20material/v13) (because only that one has references to MagicItemList). The scripts found in that folder only work with [the latest beta version that MPMB has published on his Patreon](https://www.patreon.com/posts/19406992), which is currently v13.0.0beta27.

As this is not an issue with the code, but user error, I'll be closing this issue now.
